In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("distance_and_time.csv")
df

,Unnamed: 0,name,position,total_distance,total_time
0,0,두숫놈,경기 하남시 하남대로 795,4665,3735
1,1,해장요리전문 임사부국밥 미사점,경기 하남시 미사강변한강로220번길 32 1층,748,592
2,2,바이더크릭(by the creek),"경기 하남시 미사강변중앙로 221 304호(망월동, 센트럴파크2)",1456,1213
3,3,카멜레온 다이닝(CHAMELEON DINING),경기 하남시 미사강변중앙로 193 2층 Chameleon Dining,1735,1411
4,4,낙원할머니뼛칼 본점,경기 하남시 검단로 28 202호,7317,5845
...,...,...,...,...,...
745,745,용갈집,경기 하남시 하남대로802번길 68 아트빌딩 1층,4422,3594
746,746,낙현식당,경기 하남시 하남대로 1043-28,3980,3165
747,747,호정의 식탁,"서울 송파구 올림픽로35길 124 장미종합상가 A상가 B1, 5~6호",12434,10085
748,748,천년소나무,경기 하남시 서하남로19번길 62 천년소나무,9100,7017
749,749,카페더릿(Cafe The Lit),경기 하남시 미사동로40번길 75-19 1층,1525,1240

In [4]:
cond1 = df["total_time"] <= 540
cond2 = df["total_time"] != -1

target_time_df = df.loc[cond1 & cond2]
target_time_df
# print(len(df.loc[cond1 & cond2]))

,Unnamed: 0,name,position,total_distance,total_time
6,6,청록 미나리식당 미사강변점,경기 하남시 미사강변한강로 135 다동 2층 231호,490,358
63,63,옥된장 미사스카이폴리스점,경기 하남시 미사강변한강로 135 나동 1층 0160호(스카이폴리스),490,358
96,96,봄봄 하남미사점,경기 하남시 미사강변한강로 135 나동 1층 164호,490,358
128,128,브런치&카페 알로(Brunch&Cafe allo),경기 하남시 미사강변한강로 165 AC01-25호 카페알로,381,274
148,148,박승광 해물 손칼국수 하남미사점,경기 하남시 미사강변한강로 135 스카이폴리스 다동 143호,490,358
153,153,유우조우,경기 하남시 미사강변한강로158번길 48 1층 유우조우,609,509
166,166,족발예찬 하남미사점,경기 하남시 미사강변한강로158번길 41 1층,569,451
181,181,미스터 촌돼지,경기 하남시 미사강변한강로158번안길 38 101호,479,417
217,217,동해 강릉 초당짬뽕순두부 하남미사점,경기 하남시 미사대로 380 2층,675,510
220,220,뉴욕버거 하남(SKV1)점,경기 하남시 미사강변한강로 155 111호,212,156
254,254,우나기 현,경기 하남시 미사강변한강로 155 SKV1센터 근생 102호 우나기현,212,156
259,259,망월전,경기 하남시 미사강변한강로136번길 9 1층,547,465
273,273,온담순대국 미사스카이폴리스점,경기 하남시 미사강변한강로 135 나동 1층 0155호,490,358
277,277,참토스트 하남미사점,경기 하남시 미사강변한강로 135 1층 가 133호,490,358
278,278,고집센 만두전골 두루치기,"경기 하남시 미사강변한강로 135 다동 2층 202, 203호 공원쪽",490,358
300,300,스파게티스토리 스카이폴리스점,경기 하남시 미사강변한강로 135 나동 1층 133호,490,358
306,306,별난아재맥주 하남미사점,경기 하남시 미사강변한강로158번길 52 1층 101호,623,519
311,311,화포식당 미사강변점,"경기 하남시 미사강변한강로 165 A동 216호,217호",381,274
337,337,치킨갱스터 미사점,경기 하남시 미사강변한강로 135 다동 2층 222호,490,358
353,353,솔라멘,경기 하남시 미사강변한강로 136 큰가람루 1층,616,476
362,362,카페키노(KAFE KINO),경기 하남시 미사강변한강로 135 스카이폴리스 나동 163호,490,358
366,366,스와(soir),경기 하남시 미사강변한강로136번길 25 수란가옥 1층,534,485
392,392,후라토식당 하남미사점,경기 하남시 미사강변한강로 135 스카이폴리스 다동 2층 213호,490,358
405,405,자연미당 추어탕,"경기 하남시 미사강변한강로 155 강변에스케이브이1센터 제1층 제근생141호, 14...",212,156
409,409,버거 스테이지 하남미사점,경기 하남시 미사강변한강로 135 가 119호,490,358
427,427,미사전,경기 하남시 미사강변한강로136번길 9 1층,547,465
441,441,(주)바운스 슈퍼파크 하남센터,경기 하남시 미사강변한강로 135 스카이폴리스 나동 지하1층 B151 바운스,490,358
444,444,째깍섬 키즈클래스 하남,"경기 하남시 미사강변한강로 135 미사스카이폴리스 나동 2층 251, 252호",490,358
450,450,김가네 미사스카이폴리스점,경기 하남시 미사강변한강로 135 스카이폴리스 124호,490,358
452,452,모모타코야끼 하남점,경기 하남시 미사강변한강로 135 스카이폴리스 지하1층 B170호,490,358
489,489,아리수 정육식당,경기 하남시 미사대로 380 하나로마트 하남농협 2층,675,510
546,546,마라의 민족 미사점,경기 하남시 미사강변한강로158번안길 37 102호,487,422
550,550,만차이,경기 하남시 미사강변한강로158번길 5 101 호,359,301
622,622,사미반점 미사2호점,경기 하남시 미사강변한강로 155 SK V1 센터 1층 사미반점 미사2호점,212,156
723,723,재킨보아즈,경기 하남시 미사강변한강로158번길 9 지하 1층 재킨보아즈,401,332

In [5]:
df2 = pd.read_csv("hanam_dict.csv")
df2

      Unnamed: 0     0              1
0              0     0      인생아구찜 하남점
1              1     1  아부찌부대찌개 하남감일점
2              2     2  삼백돈 돈가츠 하남미사점
3              3     3         카페 송그레
4              4     4            베르온
...          ...   ...            ...
1028        1028  1028     노랑통닭 하남덕풍점
1029        1029  1029      지코바 미사1호점
1030        1030  1030     광수육회 하남미사점
1031        1031  1031           불꾸러기
1032        1032  1032       디딤돌 숨두부집

[1033 rows x 3 columns]

In [6]:
df3 = pd.merge(left=target_time_df, right=df2, how="inner", left_on='name', right_on='1')[["name", "position", "total_distance", "total_time"]]
df3.to_csv("df_in_10min.csv")
df3

,name,position,total_distance,total_time
0,청록 미나리식당 미사강변점,경기 하남시 미사강변한강로 135 다동 2층 231호,490,358
1,옥된장 미사스카이폴리스점,경기 하남시 미사강변한강로 135 나동 1층 0160호(스카이폴리스),490,358
2,봄봄 하남미사점,경기 하남시 미사강변한강로 135 나동 1층 164호,490,358
3,브런치&카페 알로(Brunch&Cafe allo),경기 하남시 미사강변한강로 165 AC01-25호 카페알로,381,274
4,박승광 해물 손칼국수 하남미사점,경기 하남시 미사강변한강로 135 스카이폴리스 다동 143호,490,358
5,유우조우,경기 하남시 미사강변한강로158번길 48 1층 유우조우,609,509
6,족발예찬 하남미사점,경기 하남시 미사강변한강로158번길 41 1층,569,451
7,미스터 촌돼지,경기 하남시 미사강변한강로158번안길 38 101호,479,417
8,동해 강릉 초당짬뽕순두부 하남미사점,경기 하남시 미사대로 380 2층,675,510
9,뉴욕버거 하남(SKV1)점,경기 하남시 미사강변한강로 155 111호,212,156
10,우나기 현,경기 하남시 미사강변한강로 155 SKV1센터 근생 102호 우나기현,212,156
11,망월전,경기 하남시 미사강변한강로136번길 9 1층,547,465
12,온담순대국 미사스카이폴리스점,경기 하남시 미사강변한강로 135 나동 1층 0155호,490,358
13,참토스트 하남미사점,경기 하남시 미사강변한강로 135 1층 가 133호,490,358
14,고집센 만두전골 두루치기,"경기 하남시 미사강변한강로 135 다동 2층 202, 203호 공원쪽",490,358
15,스파게티스토리 스카이폴리스점,경기 하남시 미사강변한강로 135 나동 1층 133호,490,358
16,별난아재맥주 하남미사점,경기 하남시 미사강변한강로158번길 52 1층 101호,623,519
17,화포식당 미사강변점,"경기 하남시 미사강변한강로 165 A동 216호,217호",381,274
18,치킨갱스터 미사점,경기 하남시 미사강변한강로 135 다동 2층 222호,490,358
19,솔라멘,경기 하남시 미사강변한강로 136 큰가람루 1층,616,476
20,카페키노(KAFE KINO),경기 하남시 미사강변한강로 135 스카이폴리스 나동 163호,490,358
21,스와(soir),경기 하남시 미사강변한강로136번길 25 수란가옥 1층,534,485
22,후라토식당 하남미사점,경기 하남시 미사강변한강로 135 스카이폴리스 다동 2층 213호,490,358
23,자연미당 추어탕,"경기 하남시 미사강변한강로 155 강변에스케이브이1센터 제1층 제근생141호, 14...",212,156
24,버거 스테이지 하남미사점,경기 하남시 미사강변한강로 135 가 119호,490,358
25,미사전,경기 하남시 미사강변한강로136번길 9 1층,547,465
26,(주)바운스 슈퍼파크 하남센터,경기 하남시 미사강변한강로 135 스카이폴리스 나동 지하1층 B151 바운스,490,358
27,째깍섬 키즈클래스 하남,"경기 하남시 미사강변한강로 135 미사스카이폴리스 나동 2층 251, 252호",490,358
28,김가네 미사스카이폴리스점,경기 하남시 미사강변한강로 135 스카이폴리스 124호,490,358
29,모모타코야끼 하남점,경기 하남시 미사강변한강로 135 스카이폴리스 지하1층 B170호,490,358
30,아리수 정육식당,경기 하남시 미사대로 380 하나로마트 하남농협 2층,675,510
31,마라의 민족 미사점,경기 하남시 미사강변한강로158번안길 37 102호,487,422
32,만차이,경기 하남시 미사강변한강로158번길 5 101 호,359,301
33,사미반점 미사2호점,경기 하남시 미사강변한강로 155 SK V1 센터 1층 사미반점 미사2호점,212,156
34,재킨보아즈,경기 하남시 미사강변한강로158번길 9 지하 1층 재킨보아즈,401,332

In [7]:
df4 = pd.read_csv("category.csv")
df4

     Unnamed: 0                        name category3
0             0                         두숫놈        식당
1             1            해장요리전문 임사부국밥 미사점       한식당
2             2         바이더크릭(by the creek)        호프
3             3  카멜레온 다이닝(CHAMELEON DINING)        식당
4             4                  낙원할머니뼛칼 본점       한식당
..          ...                         ...       ...
994         994                    장다리 한우마당        고기
995         995                    이정수치킨전문점        치킨
996         996                    소문난손칼국수집        분식
997         997                     피맥 플레이스        피자
998         998                        구림장어        해물

[999 rows x 3 columns]

In [9]:
df5 = pd.merge(df3, df4, how="inner")[["name", "position", "total_distance", "total_time", "category3"]]
df5.to_csv("df_in_10min_v2.csv")